# Generated by Django 5.2.7 on 2026-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='chat_response_time',
            field=models.CharField(blank=True, default='24 hours', max_length=50, null=True),
        ),
    ]
